/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as RoteirosRouteImport } from './routes/roteiros'
import { Route as CompartilhadoDataRouteImport } from './routes/compartilhado.$data'
import { Route as RoteiroIdRouteImport } from './routes/roteiro.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const RoteirosRoute = RoteirosRouteImport.update({
  id: '/roteiros',
  path: '/roteiros',
  getParentRoute: () => rootRouteImport,
} as any)
const CompartilhadoDataRoute = CompartilhadoDataRouteImport.update({
  id: '/compartilhado/$data',
  path: '/compartilhado/$data',
  getParentRoute: () => rootRouteImport,
} as any)
const RoteiroIdRoute = RoteiroIdRouteImport.update({
  id: '/roteiro/$id',
  path: '/roteiro/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/criar': typeof CriarRoute
  '/roteiros': typeof RoteirosRoute
  '/compartilhado/$data': typeof CompartilhadoDataRoute
  '/roteiro/$id': typeof RoteiroIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/criar': typeof CriarRoute
  '/roteiros': typeof RoteirosRoute
  '/compartilhado/$data': typeof CompartilhadoDataRoute
  '/roteiro/$id': typeof RoteiroIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/criar': typeof CriarRoute
  '/roteiros': typeof RoteirosRoute
  '/compartilhado/$data': typeof CompartilhadoDataRoute
  '/roteiro/$id': typeof RoteiroIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-funciona'
    | '/criar'
    | '/roteiros'
    | '/compartilhado/$data'
    | '/roteiro/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-funciona'
    | '/criar'
    | '/roteiros'
    | '/compartilhado/$data'
    | '/roteiro/$id'
  id:
    | '__root__'
    | '/'
    | '/como-funciona'
    | '/criar'
    | '/roteiros'
    | '/compartilhado/$data'
    | '/roteiro/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  CriarRoute: typeof CriarRoute
  RoteirosRoute: typeof RoteirosRoute
  CompartilhadoDataRoute: typeof CompartilhadoDataRoute
  RoteiroIdRoute: typeof RoteiroIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roteiros': {
      id: '/roteiros'
      path: '/roteiros'
      fullPath: '/roteiros'
      preLoaderRoute: typeof RoteirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compartilhado/$data': {
      id: '/compartilhado/$data'
      path: '/compartilhado/$data'
      fullPath: '/compartilhado/$data'
      preLoaderRoute: typeof CompartilhadoDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roteiro/$id': {
      id: '/roteiro/$id'
      path: '/roteiro/$id'
      fullPath: '/roteiro/$id'
      preLoaderRoute: typeof RoteiroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  CriarRoute: CriarRoute,
  RoteirosRoute: RoteirosRoute,
  CompartilhadoDataRoute: CompartilhadoDataRoute,
  RoteiroIdRoute: RoteiroIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
